// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGViN12HnUDSED1jl2sbVYDtiW4iPPN9U',
    appId: '1:384236006451:web:23a5d839d130d9f6914746',
    messagingSenderId: '384236006451',
    projectId: 'comms-app-14c8f',
    authDomain: 'comms-app-14c8f.firebaseapp.com',
    storageBucket: 'comms-app-14c8f.appspot.com',
    measurementId: 'G-TFDVXKLRNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fSlZtNiPwUwC6PIZPFz2z7dKauQZXWk',
    appId: '1:384236006451:android:f7c1745494ba1b7f914746',
    messagingSenderId: '384236006451',
    projectId: 'comms-app-14c8f',
    storageBucket: 'comms-app-14c8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutksJiHRQl0LHSRbCy1cQLb9HtnppC9c',
    appId: '1:384236006451:ios:438e1f02b1ce149d914746',
    messagingSenderId: '384236006451',
    projectId: 'comms-app-14c8f',
    storageBucket: 'comms-app-14c8f.appspot.com',
    iosClientId: '384236006451-2ddt3tvls20osdrb9trk7ui7e12q56cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.commsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAutksJiHRQl0LHSRbCy1cQLb9HtnppC9c',
    appId: '1:384236006451:ios:db0d0c0b22e0226e914746',
    messagingSenderId: '384236006451',
    projectId: 'comms-app-14c8f',
    storageBucket: 'comms-app-14c8f.appspot.com',
    iosClientId: '384236006451-275hbjrqc5h0cqvjk9aqi4u1u4h5qunn.apps.googleusercontent.com',
    iosBundleId: 'com.example.commsApp.RunnerTests',
  );
}
